
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_automotivo
    restart: unless-stopped
    ports:
      - "80:80"      
      
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge